### ISSUE TITLE
Ps4 Issue

### ISSUE THREAD

**Issue by kisaapear** [DaPigGuy/PiggyAuctions#11]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyAuctions
- * [ ] Have a detailed title (i.e "Auctioned items remain in inventory")

### Issue Description

- Expected result: What were you expecting to happen? Do /ah and gui suppose to show up
- Actual result: What actually happened? Nothing showed up

#### Steps to Reproduce the Issue
1. ... Use ps4
2. ... Run /ah

### OS and Versions

* PocketMine-MP: Latest
* PiggyAuctions: Latest
* PHP:
* Server OS:

### Extra Information
This issue seems to be happening to ps4 players only

**Comment by DaPigGuy** [comment]
Please give the name of the PiggyAuctions version. Latest is not sufficient.

**Comment by kisaapear** [comment]
Dev 33, and sorry here is the video https://youtu.be/yZo37n2b4eE

**Comment by Aericio** [comment]
Did you restart the server, or did you use /reload?

**Comment by Aericio** [comment]
This issue could not be reproduced, at least on an Xbox One X.

Most likely, you used `/reload` to install the plugin which caused the virion InvMenu to stop working.

**Comment by kisaapear** [comment]
nope i dont use /reload but okay

**Comment by DaPigGuy** [comment]
This issue should be fixed on PiggyAuctions v1.0.8
