### ISSUE TITLE
Auction Sniping

### ISSUE THREAD

**Issue by kisaapear** [DaPigGuy/PiggyAuctions#12]
Please make sure your issue complies with these guidelines:
- * [ ] Idea must have not been suggested previously
- * [ ] Be detailed on what you want & make sure the idea is plausible

### Description

Please add a feature where if player bid under 30 seconds (or when the auction almost end) the timer increase back to a minute to prevent people from sniping the auction in the last second

### Extra Information

**Comment by VoltageMC** [comment]
Good idea
