### ISSUE TITLE
Mobile Dupe Glitch

### ISSUE THREAD

**Issue by Siol-GTM** [DaPigGuy/PiggyAuctions#14]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyAuctions
- * [ ] Have a detailed title (i.e "Auctioned items remain in inventory")

### Issue Description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

#### Steps to Reproduce the Issue
1. ...
2. ...

### OS and Versions

* PocketMine-MP: 3.11.6
* PiggyAuctions: Dev 41
* PHP:
* Server OS:

### Extra Information

https://twitter.com/whamenrespek/status/1249065778235748358?s=19

**Comment by pleasepoggitwork** [comment]
Very desciptive!

**Comment by DaPigGuy** [comment]
Use 1.0.4
