### ISSUE TITLE
Item duplication bug

### ISSUE THREAD

**Issue by CaptainDuck** [DaPigGuy/PiggyAuctions#18]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyAuctions
- * [x] Have a detailed title.

### Issue Description

- Expected result: The auction will be cancelled and the item won't still be at the menu.
- Actual result: Item was still in the menu and the cancelled item was given to the inventory causing the dupe.

#### Steps to Reproduce the Issue
[--]

### OS and Versions

* PocketMine-MP:
* PiggyAuctions:
* PHP:
* Server OS:

### Extra Information

**Comment by Aericio** [comment]
We are unable to view the video, seems to have been deleted. 
- Please upload the video to https://streamable.com/ instead, no account required.
- Fill out the "OS and Versions" section.

**Comment by CaptainDuck** [comment]
https://streamable.com/nrdye0

**Comment by Aericio** [comment]
We were unable to reproduce the issue with the version `1.0.4`. This issue will be closed until you provide us with version information.

**Comment by CaptainDuck** [comment]
Latest, version `PiggyAuctions v1.0.4`.
Using PHP 7.3, Linux as OS and the latest stable PMMP release.

**Comment by CaptainDuck** [comment]
Could you explain more about how you weren't able to reproduce the bug?

I can explain it more clearly:
1. Go to Create Auction menu, enter the item then click confirm.
2. In the Confirm Menu, simply cancel it then you will be reverted back to the Create Auction menu where the same item will be added in the inventory while it is also at the display auction menu.

**Comment by Aericio** [comment]
Issue was reproduced, but we don't want to get into specifics until the fix is released.

**Comment by Aericio** [comment]
Issue was fixed: https://github.com/DaPigGuy/PiggyAuctions/commit/5dbf3408f9cf7cc44a71a214b6633801a6bfb572
