### ISSUE TITLE
Forms not showing up

### ISSUE THREAD

**Issue by rjworks** [DaPigGuy/PiggyAuctions#20]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyAuctions
- * [ ] Have a detailed title.

### Issue Description

- Expected result: What were you expecting to happen?
edit item price and actually put it on bid
- Actual result: What actually happened?
nothing happens after editing the price, just took my item
#### Steps to Reproduce the Issue
1. open /ah
2. create an auction
3, hit edit starting bid
4. nothing happens, just takes away my item

### OS and Versions

* PocketMine-MP: 3.14.2
* PiggyAuctions: 1.0.6
* PHP:64
* Server OS:windows

### Extra Information
was this not tasted at all?

**Comment by NicoBooze** [comment]
same problem!

**Comment by Aericio** [comment]
Latest version fixed menus and therefore only menus were tested. Not sure why forms are broken, sometime it'll show up and sometimes it wont.

**Comment by Aericio** [comment]
> Allows you to specify a closure that gets triggered after escaping from the even call stack and the client's network stack. This is useful when you need to do something like sending a form to a player (it isn't possible to send a form before or right after closing their inventory).
> https://github.com/Muqsit/InvMenu/wiki/InvMenu-v4.0#the-invmenutransactionresultthen-method

Seems like it'll be fixed in InvMenu v4.0, but v4.0 is only available for PMMP API 4.0.0. Can't do anything for now.

**Comment by rjworks** [comment]
when is pm4.0.0 releases though

**Comment by Aericio** [comment]
Sorry, can't see the future.

**Comment by itshakankaya** [comment]
Same with duration...And it never shows i tried it like 20 times.

**Comment by rjworks** [comment]
> Sorry, can't see the future.

Create a delayed task?
