### ISSUE TITLE
It crashes when you open it in 1.16

### ISSUE THREAD

**Issue by deft846** [DaPigGuy/PiggyAuctions#21]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyAuctions
- * [ ] Have a detailed title.

### Issue Description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

#### Steps to Reproduce the Issue
1. ...
2. ...

### OS and Versions

* PocketMine-MP:
* PiggyAuctions:
* PHP:
* Server OS:

### Extra Information

**Comment by Aericio** [comment]
#20
