### ISSUE TITLE
2 server with mysql is not working

### ISSUE THREAD

**Issue by efor89** [DaPigGuy/PiggyAuctions#27]
hi

if i use the plugin on 2 server with mysql it dont refresh.
i put an auction in 1 cb and dont see it on the other cb but if i restart the server i see it but... the seller or the buyer become the item on cb1 and cb2 thats a rly bad dup bug
and make the mysql db useless

plz make a mysql refreshtask

**Comment by Aericio** [comment]
Was never intended to be used by multiple servers at once.
