### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by PLUGINTESTER** [DaPigGuy/PiggyAuctions#29]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyAuctions
- * [ ] Have a detailed title.

### Issue Description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

#### Steps to Reproduce the Issue
1.  It show internal server error
2. and plugin has LATEST VERSION

### OS and Versions

* PocketMine-MP:
* PiggyAuctions:
* PHP:
* Server OS:

### Extra Information

**Comment by Aericio** [comment]
download invcrashfix plugin https://github.com/DaPigGuy/PiggyAuctions#notice
