### ISSUE TITLE
GUI sometimes does not pop up

### ISSUE THREAD

**Issue by kisaapear** [DaPigGuy/PiggyAuctions#3]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyAuctions
- * [ ] Have a detailed title (i.e "Auctioned items remain in inventory")

### Issue Description
https://youtu.be/2pLAv2-RGE4

- Expected result: Open up a gui page
- Actual result: GUI disappear

#### Steps to Reproduce the Issue
1. Do /ah
2. Click on the option

### OS and Versions

* PocketMine-MP: Latest
* PiggyAuctions: Dev 9 (Latest)
* PHP:
* Server OS:

### Extra Information

**Comment by DaPigGuy** [comment]
What version of Minecraft Bedrock are you on?

**Comment by kisaapear** [comment]
> What version of Minecraft Bedrock are you on?

**Comment by DaPigGuy** [comment]
?

**Comment by DaPigGuy** [comment]
Why did you close the issue?

**Comment by kisaapear** [comment]
> ?

Sorry i updated the comment
