### ISSUE TITLE
Error: "Class 'Ds\Queue' not found"

### ISSUE THREAD

**Issue by MineGuy112** [DaPigGuy/PiggyAuctions#36]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyAuctions
- * [x] Have a detailed title.

Link to Crashdump: 
https://hastebin.com/iyurababep.yaml

### Extra Information
It occurs when a player joins the server. It's also exactly the same error that used to be on PiggyCrates.

**Comment by Aericio** [comment]
Use 1.0.9

https://github.com/DaPigGuy/PiggyAuctions/releases/tag/1.0.9
