### ISSUE TITLE
Server Crashed

### ISSUE THREAD

**Issue by DaDevGuy** [DaPigGuy/PiggyAuctions#45]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyAuctions
- * [x] Have a detailed title.

Link to Crashdump: 
https://www.toptal.com/developers/hastebin/imokelileh.scss

### Extra Information

**Comment by DaPigGuy** [comment]
Empty hastebin

**Comment by DaDevGuy** [comment]
Fixed i didnt uploaded virions my bad
