### ISSUE TITLE
Erorr

### ISSUE THREAD

**Issue by Wayder228** [DaPigGuy/PiggyAuctions#49]
Piggy auction does not open, after which the inventory does not work.

**Comment by Aericio** [comment]
please read here 

https://github.com/DaPigGuy/PiggyAuctions#invcrashfix-is-still-needed

**Comment by Wayder228** [comment]
> пожалуйста, прочитайте здесь
> 
> [https://github.com/DaPigGuy/PiggyAuctions#invcrashfix-is-по-прежнему необходим](https://github.com/DaPigGuy/PiggyAuctions#invcrashfix-is-still-needed)

I know he's standing by me! But sernovno does not work, maybe it does not support  1.18.30?
