### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ImAFishKid** [DaPigGuy/PiggyAuctions#52]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyAuctions
- * [ ] Have a detailed title.

Link to Crashdump: 

### Extra Information

**Comment by Thunder33345** [comment]
closing because there's no actual information provided
please fill in the given template
