### ISSUE TITLE
I can't create auction

### ISSUE THREAD

**Issue by OurFirstStep** [DaPigGuy/PiggyAuctions#7]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyAuctions
- * [ ] Have a detailed title (i.e "Auctioned items remain in inventory")

### Issue Description

- Expected result: Creating Auction
- Actual result: Nothing happened

#### Steps to Reproduce the Issue
1./ah
2.Click [Manage Auctions]
3.Click [Create Auction] , while holding an item.
4.Clicking [Create Auction] doesn't work.
  Not showing new page, It just doesn't change.
  No crashdumps created.

### OS and Versions

* PocketMine-MP: 3.11.6 latest
* PiggyAuctions: latest
* PHP:
* Server OS:

### Extra Information

**Comment by DaPigGuy** [comment]
Use build 19 here: https://poggit.pmmp.io/ci/DaPigGuy/PiggyAuctions/~

**Comment by OurFirstStep** [comment]
> Use build 19 here: https://poggit.pmmp.io/ci/DaPigGuy/PiggyAuctions/~

 I already used that version.
