### ISSUE TITLE
UI not well designed for Pocket UI

### ISSUE THREAD

**Issue by bubbakadriu** [DaPigGuy/PiggyAuctions#8]
Hi so we press the "Create Auction" button and its doing nothing

**Comment by Aericio** [comment]
Which version are you using?

**Comment by bubbakadriu** [comment]
The one that is newest to poggit, i downloaded it 10 mins ago

**Comment by bubbakadriu** [comment]
Do we have to hold the item we want to add to the ah before we can create it?

**Comment by bubbakadriu** [comment]
I have 4 other people having same issue

**Comment by Aericio** [comment]
Do you have screen animations enabled?

**Comment by bubbakadriu** [comment]
Not to sure what that is or how to enable it

**Comment by Aericio** [comment]
In Minecraft settings, it is enabled by default.

**Comment by bubbakadriu** [comment]
Then yes id assume its enabled

**Comment by Aericio** [comment]
Please try to disable it and see if it works after.

**Comment by DaPigGuy** [comment]
Please provide a video of this issue happening

**Comment by bubbakadriu** [comment]
It isnt letting me send it here, can you dm me on discord @Bubba0695

**Comment by DaPigGuy** [comment]
Join the [Discord server ](https://discord.gg/qmnDsSD) and send the video there

**Comment by bubbakadriu** [comment]
I sent you a dm

**Comment by TheUtopianPlayz** [comment]
Pocket edition players don't know that there's a specific spot they have to put the item in, because every slot *Looks* empty and it looks like they can put the item in because they don't know the right slot, or they don't even know they have to put the item in because of that fact, I would recommend swapping the "empty slots" with a color of class pain so people know which slot is *actually* empty

**Comment by DaPigGuy** [comment]
Unfortunately with Bedrock Edition, stained glass panes have a 3D texture and not the 2D texture of Java edition

**Comment by DaPigGuy** [comment]
An alternative would be invisible bedrock

![image](https://user-images.githubusercontent.com/8540562/78197412-1c4db000-743a-11ea-9b18-ce2b104bced9.png)

**Comment by Aericio** [comment]
Make it configurable, and we'll have two item ids that we recommend to be used?

**Comment by DaPigGuy** [comment]
The above change is now available on the latest development build on Poggit. This issue will remain open as the UI in general was poorly designed for Pocket UI

**Comment by OurFirstStep** [comment]
How do you comfirm auction ? 
Red block doesn't work .....
